# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqcEg8qL1J291NeyxKPNHBsIRaKohNRz
"""

import streamlit as st
from kiwipiepy import Kiwi

# ──────────────────────────────────────────────────────
# 기본 설정
# ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="MLU-w 게임 & MLU 분석기",
    layout="centered"
)

# 연보라 버튼 스타일
st.markdown("""
<style>
div.stButton > button {
    background-color: #D8B4F8;
    color: white;
    border: none;
    border-radius: 12px;
    padding: 0.5em 1em;
    font-weight: bold;
}
div.stButton > button:hover {
    background-color: #C084FC;
    color: white;
}
</style>
""", unsafe_allow_html=True)

# ──────────────────────────────────────────────────────
# Kiwi 객체 캐시
# ──────────────────────────────────────────────────────
@st.cache_resource
def get_kiwi():
    return Kiwi()

kiwi = get_kiwi()

# ──────────────────────────────────────────────────────
# 태그 정규화 (Kiwi는 불규칙 활용을 'VV-I', 'XSA-I' 등으로 태그함)
# ──────────────────────────────────────────────────────
def base_tag(tag):
    """'VV-I' → 'VV', 'XSA-I' → 'XSA' 처럼 접미사를 떼어낸 기본 태그를 반환."""
    return tag.split('-')[0]

# ──────────────────────────────────────────────────────
# 분석 기준 정의 (MLU-w, MLU-m) - 사용자 제공 기준 적용
# ──────────────────────────────────────────────────────
# 문장부호·기호 (MLU-m 계산에서 제외)
PUNCT_TAGS = {'SF', 'SP', 'SS', 'SE', 'SO', 'SW', 'SB', 'UNKNOWN'}

# 학교문법 기반 '단어' 단위 태그 정의 (MLU-w 산정용)
WORD_TAGS = {
    # 체언
    'NNG', 'NNP', 'NNB', 'NP', 'NR',
    # 용언 (어간 = 단어 1)
    'VV', 'VA', 'VX', 'VCP', 'VCN',
    # 수식언
    'MM', 'MAG', 'MAJ',
    # 독립언
    'IC',
    # 조사 (학교문법에서 단어로 인정)
    'JKS', 'JKC', 'JKG', 'JKO', 'JKB', 'JKV', 'JKQ', 'JX', 'JC',
    # 자립형식
    'SL', 'SH', 'SN',
}

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수 (학교 문법 '단어' 기준) 및 MLU-m 분석 추가
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]

    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = [] # For MLU-w
    utterance_morph_counts = [] # For MLU-m

    for i, utt in enumerate(utterances):
        tokens = kiwi.tokenize(utt)

        word_count = 0  # Based on WORD_TAGS
        morph_count = 0 # Based on non-PUNCT_TAGS

        for token in tokens:
            tag_base = base_tag(token.tag)
            if tag_base in WORD_TAGS:
                word_count += 1
            if tag_base not in PUNCT_TAGS: # MLU-m counts all morphemes, excluding punctuation
                morph_count += 1

        utterance_word_counts.append(word_count)
        utterance_morph_counts.append(morph_count)

        utterance_details.append(
            f" - 발화 {i+1}: '{utt}' (단어수: {word_count}, 형태소수: {morph_count})"
        )

    total_utterances = len(utterances)
    mlu_w_calculated = sum(utterance_word_counts) / total_utterances
    mlu_m_calculated = sum(utterance_morph_counts) / total_utterances

    mlu_w_rounded = round(mlu_w_calculated, 2)
    mlu_m_rounded = round(mlu_m_calculated, 2)

    return {
        "utterance_details": utterance_details,
        "total_utterances": total_utterances,
        "mlu_w": mlu_w_rounded,
        "mlu_m": mlu_m_rounded
    }, utterances


# ──────────────────────────────────────────────────────
# 문제 데이터
# ──────────────────────────────────────────────────────
questions = [
    {"sentence": "엄마 저 피자랑 고구마 주세요. 맛있게 구워 주세요.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "형아 나 밥. 나 배고파.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "아빠랑 공원에 갔어요. 시소 타고 미끄럼틀도 탔어요.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "맛있는 케이크 먹고 싶어요. 선물로 주세요.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "엄마 하늘 봐요. 하늘에 반짝해요. 별이 정말 예뻐요.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "동생이 내 장난감 가지고 놀아요. 저 화가 났어요.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "엄마 나랑 놀아. 아빠도 놀아.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "이건 내 거야. 건들지 마.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "너는 왜 혼자야? 나랑 놀자.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "우리 나중에 결혼하자. 약속해.", "mluw": 0.0, "mlum": 0.0},
    {"sentence": "엄마랑 놀래. 우리 놀이터 가자.", "mluw": 0.0, "mlum": 0.0}
]

# ──────────────────────────────────────────────────────
# 업데이트된 MLU-w 및 MLU-m 기준으로 문제 정답 재계산
# ──────────────────────────────────────────────────────
for q_data in questions:
    analysis_result, _ = run_mluw_analysis(q_data["sentence"])
    if analysis_result:
        q_data["mluw"] = analysis_result["mlu_w"]
        q_data["mlum"] = analysis_result["mlu_m"]


# ──────────────────────────────────────────────────────
# 세션 상태 초기화
# ──────────────────────────────────────────────────────
if "current_question_index" not in st.session_state:
    st.session_state.current_question_index = 0

if "feedback_message" not in st.session_state:
    st.session_state.feedback_message = ""

if "result_message" not in st.session_state:
    st.session_state.result_message = ""

if "show_input" not in st.session_state:
    st.session_state.show_input = True

if "show_next_button" not in st.session_state:
    st.session_state.show_next_button = False

if "user_mlu_input" not in st.session_state: # Changed key from user_mluw_input
    st.session_state.user_mlu_input = ""

if "initial_load" not in st.session_state:
    st.session_state.initial_load = True

if "score" not in st.session_state:
    st.session_state.score = 0

if "game_started" not in st.session_state:
    st.session_state.game_started = False

if "game_type" not in st.session_state: # New session state for game type
    st.session_state.game_type = "mlu_w" # Default to MLU-w game


# ──────────────────────────────────────────────────────
# 게임 함수
# ──────────────────────────────────────────────────────
def load_question():
    st.session_state.feedback_message = ""
    st.session_state.result_message = ""
    st.session_state.user_mlu_input = "" # Changed key
    st.session_state.show_input = True
    st.session_state.show_next_button = False

def reset_game_callback():
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.game_started = False
    load_question()

def start_game_callback(game_type_selected): # Added argument for game type
    st.session_state.game_started = True
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    st.session_state.game_type = game_type_selected # Set game type
    load_question()

def check_answer_callback():
    q_data = questions[st.session_state.current_question_index]
    user_answer = st.session_state.user_mlu_input.strip() # Changed key

    if not user_answer:
        st.session_state.feedback_message = "MLU 값을 입력해주세요!"
        return

    try:
        user_mlu = float(user_answer)
    except ValueError:
        st.session_state.feedback_message = "유효한 숫자를 입력해주세요!"
        return

    correct_mlu = 0.0
    mlu_type_str = "MLU"

    if st.session_state.game_type == "mlu_w":
        correct_mlu = q_data["mluw"]
        mlu_type_str = "MLU-w"
    elif st.session_state.game_type == "mlu_m":
        correct_mlu = q_data["mlum"]
        mlu_type_str = "MLU-m"

    if abs(user_mlu - correct_mlu) < 0.01:
        st.session_state.feedback_message = "정답입니다!"
        st.session_state.score += 1
    else:
        st.session_state.feedback_message = "오답입니다."

    st.session_state.result_message = f"정답 {mlu_type_str}: {correct_mlu}"
    st.session_state.show_input = False
    st.session_state.show_next_button = True


def next_problem_callback():
    st.session_state.current_question_index += 1
    load_question()



# ──────────────────────────────────────────────────────
# 초기 문제 로드
# ──────────────────────────────────────────────────────
if st.session_state.initial_load:
    load_question()
    st.session_state.initial_load = False


# ──────────────────────────────────────────────────────
# UI
# ──────────────────────────────────────────────────────
st.title("MLU 게임!♡")

mode = st.sidebar.radio(
    "모드를 선택하세요:",
    ("MLU-w 게임", "MLU-m 게임", "MLU 분석기 (자유 입력)") # Added MLU-m Game
)

if mode == "MLU-w 게임":
    st.markdown("제시된 문장의 MLU-w(학교 문법 '단어' 기준)를 계산하여 입력하세용가리.")
    st.caption("소수점 둘째 자리까지 입력하세욥. (예: 2.67)")

    if not st.session_state.game_started or st.session_state.game_type != "mlu_w":
        st.subheader("MLU-w 게임에 오신 것을 환영합니다! ♡")
        st.write("시작하기 버튼을 누르면 문제가 시작됩니다.")
        st.button("시작하기", on_click=lambda: start_game_callback("mlu_w"))

    elif st.session_state.current_question_index >= len(questions):
        st.header("모든 문제를 다 풀었습니다!")
        st.subheader(f"최종 점수: {st.session_state.score}/{len(questions)}")

        if st.session_state.score == len(questions):
            st.balloons()
            st.success("완벽해용! 전부 맞혔어요♡")
        elif st.session_state.score >= 7:
            st.success("잘했어용! 아주 훌륭해요♡")
        else:
            st.info("수고했어용! 다시 도전해볼까요?")

        st.button("처음으로", on_click=reset_game_callback)

    else:
        q_data = questions[st.session_state.current_question_index]

        st.subheader(f'문제: "{q_data["sentence"]}"')

        if st.session_state.show_input:
            st.text_input(
                "MLU-w를 입력하세요",
                key="user_mlu_input" # Changed key
            )

            st.button(
                "정답 확인",
                on_click=check_answer_callback
            )

        if st.session_state.feedback_message:
            st.write(st.session_state.feedback_message)

        if st.session_state.result_message:
            st.write(st.session_state.result_message)

        col1, col2 = st.columns(2);

        with col1:
            if st.session_state.show_next_button:
                st.button(
                    "다음으로",
                    on_click=next_problem_callback # Corrected on_on_click to on_click
                )

        with col2:
            st.button(
                "처음으로",
                on_click=reset_game_callback
            )

elif mode == "MLU-m 게임": # New MLU-m Game Mode
    st.markdown("제시된 문장의 MLU-m(문장부호 제외 형태소 기준)을 계산하여 입력하세용가리.")
    st.caption("소수점 둘째 자리까지 입력하세욥. (예: 3.25)")

    if not st.session_state.game_started or st.session_state.game_type != "mlu_m":
        st.subheader("MLU-m 게임에 오신 것을 환영합니다! ♡")
        st.write("시작하기 버튼을 누르면 문제가 시작됩니다.")
        st.button("시작하기", on_click=lambda: start_game_callback("mlu_m"))

    elif st.session_state.current_question_index >= len(questions):
        st.header("모든 문제를 다 풀었습니다!")
        st.subheader(f"최종 점수: {st.session_state.score}/{len(questions)}")

        if st.session_state.score == len(questions):
            st.balloons()
            st.success("완벽해용! 전부 맞혔어요♡")
        elif st.session_state.score >= 7:
            st.success("잘했어용! 아주 훌륭해요♡")
        else:
            st.info("수고했어용! 다시 도전해볼까요?")

        st.button("처음으로", on_click=reset_game_callback)

    else:
        q_data = questions[st.session_state.current_question_index]

        st.subheader(f'문제: "{q_data["sentence"]}"')

        if st.session_state.show_input:
            st.text_input(
                "MLU-m을 입력하세요",
                key="user_mlu_input" # Reused key
            )

            st.button(
                "정답 확인",
                on_click=check_answer_callback
            )

        if st.session_state.feedback_message:
            st.write(st.session_state.feedback_message)

        if st.session_state.result_message:
            st.write(st.session_state.result_message)

        col1, col2 = st.columns(2);

        with col1:
            if st.session_state.show_next_button:
                st.button(
                    "다음으로",
                    on_click=next_problem_callback
                )

        with col2:
            st.button(
                "처음으로",
                on_click=reset_game_callback
            )

elif mode == "MLU 분석기 (자유 입력)":
    st.subheader("MLU-w 및 MLU-m 분석기")
    st.write("분석하고 싶은 문장을 입력하세요.")

    input_text = st.text_area("문장 입력", key="analyzer_input", height=150)

    if st.button("분석하기"):
        if input_text:
            analysis_result, _ = run_mluw_analysis(input_text)
            if analysis_result:
                st.markdown("---")
                st.write("**분석 결과:**")
                for detail in analysis_result['utterance_details']:
                    st.write(detail)
                st.write(f"총 발화 수: {analysis_result['total_utterances']}")
                st.success(f"계산된 MLU-w: {analysis_result['mlu_w']}")
                st.info(f"계산된 MLU-m: {analysis_result['mlu_m']}")
            else:
                st.warning("분석할 유효한 발화가 없습니다.")
        else:
            st.warning("분석할 문장을 입력해주세요.")