# -*- coding: utf-8 -*-
"""엠엘류게임.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8wGcAgG5OGJ4EYSYQugZQE3p_HQV4p_
"""

# app.py
import streamlit as st
from kiwipiepy import Kiwi

# ──────────────────────────────────────────────────────
# 기본 설정
# ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="MLU-w를 맞혀라! (kiwipiepy 기반)",
    layout="centered"
)

st.title("MLU-w를 맞혀라!♡ (kiwipiepy 기반)")
st.markdown("제시된 문장의 MLU-w(어절 기준)를 계산하여 입력하세요.")
st.caption("소수점 둘째 자리까지 입력하세요. (예: 2.67)")


# 연보라 버튼 스타일
st.markdown("""
<style>
div.stButton > button {
    background-color: #D8B4F8;
    color: white;
    border: none;
    border-radius: 12px;
    padding: 0.5em 1em;
    font-weight: bold;
}
div.stButton > button:hover {
    background-color: #C084FC;
    color: white;
}
</style>
""", unsafe_allow_html=True)

# ──────────────────────────────────────────────────────
# Kiwi 객체 캐시
# ──────────────────────────────────────────────────────
@st.cache_resource
def get_kiwi():
    return Kiwi()

kiwi = get_kiwi()

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수 (어절 기준)
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]

    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = []

    for i, utt in enumerate(utterances):
        # 어절 기준 계산
        word_count = len(utt.split())
        utterance_word_counts.append(word_count)

        utterance_details.append(
            f" - 발화 {i+1}: '{utt}' (어절수: {word_count})"
        )

    total_utterances = len(utterances)
    average_word_count = sum(utterance_word_counts) / total_utterances
    mlu_w = round(average_word_count, 2)

    return {
        "utterance_details": utterance_details,
        "total_utterances": total_utterances,
        "mlu_w": mlu_w
    }, utterances


# ──────────────────────────────────────────────────────
# 문제 데이터
# ──────────────────────────────────────────────────────
questions = [
    {"sentence": "엄마 저 피자랑 고구마 주세요. 맛있게 구워 주세요.", "mluw": 4.5},
    {"sentence": "형아 나 밥. 나 배고파.", "mluw": 2.5},
    {"sentence": "아빠랑 공원에 갔어요. 시소 타고 미끄럼틀도 탔어요.", "mluw": 5},
    {"sentence": "맛있는 케이크 먹고 싶어요. 선물로 주세요.", "mluw": 3.5},
    {"sentence": "엄마 하늘 봐요. 하늘에 반짝해요. 별이 정말 예뻐요.", "mluw": 3.33},
    {"sentence": "동생이 내 장난감 가지고 놀아요. 저 화가 났어요.", "mluw": 5},
    {"sentence": "엄마 나랑 놀아. 아빠도 놀아.", "mluw": 3.5},
    {"sentence": "이건 내 거야. 건들지 마.", "mluw": 3.5},
    {"sentence": "너는 왜 혼자야? 나랑 놀자.", "mluw": 4},
    {"sentence": "우리 나중에 결혼하자. 약속해.", "mluw": 2.5},
]

# ──────────────────────────────────────────────────────
# 세션 상태 초기화
# ──────────────────────────────────────────────────────
if "current_question_index" not in st.session_state:
    st.session_state.current_question_index = 0

if "feedback_message" not in st.session_state:
    st.session_state.feedback_message = ""

if "result_message" not in st.session_state:
    st.session_state.result_message = ""

if "show_input" not in st.session_state:
    st.session_state.show_input = True

if "show_next_button" not in st.session_state:
    st.session_state.show_next_button = False

if "user_mluw_input" not in st.session_state:
    st.session_state.user_mluw_input = ""

if "initial_load" not in st.session_state:
    st.session_state.initial_load = True

if "score" not in st.session_state:
    st.session_state.score = 0


# ──────────────────────────────────────────────────────
# 게임 함수
# ──────────────────────────────────────────────────────
def load_question():
    st.session_state.feedback_message = ""
    st.session_state.result_message = ""
    st.session_state.user_mluw_input = ""
    st.session_state.show_input = True
    st.session_state.show_next_button = False


def check_answer_callback():
    q_data = questions[st.session_state.current_question_index]
    user_answer = st.session_state.user_mluw_input.strip()

    if not user_answer:
        st.session_state.feedback_message = "MLU-w 값을 입력해주세요!"
        return

    try:
        user_mluw = float(user_answer)
    except ValueError:
        st.session_state.feedback_message = "유효한 숫자를 입력해주세요!"
        return

    correct_mluw = q_data["mluw"]

    if abs(user_mluw - correct_mluw) < 0.01:
        st.session_state.feedback_message = "정답입니다!"
        st.session_state.score += 1
    else:
        st.session_state.feedback_message = "오답입니다."

    st.session_state.result_message = f"정답 MLU-w: {correct_mluw}"
    st.session_state.show_input = False
    st.session_state.show_next_button = True


def next_problem_callback():
    st.session_state.current_question_index += 1
    load_question()


def reset_game_callback():
    st.session_state.current_question_index = 0
    st.session_state.score = 0
    load_question()


# ──────────────────────────────────────────────────────
# 초기 문제 로드
# ──────────────────────────────────────────────────────
if st.session_state.initial_load:
    load_question()
    st.session_state.initial_load = False


# ──────────────────────────────────────────────────────
# UI
# ──────────────────────────────────────────────────────
if st.session_state.current_question_index >= len(questions):
    st.header("모든 문제를 다 풀었습니다!")
    st.subheader(f"최종 점수: {st.session_state.score}/{len(questions)}")

if st.session_state.score == len(questions):
        st.balloons()
        st.success("완벽해요! 전부 맞혔어요! ♡")
elif st.session_state.score >= 7:
        st.success("잘했어요! 아주 훌륭해요! ♡")
else:
        st.info("수고했어요! 다시 도전해볼까요?")

    st.button("처음으로", on_click=reset_game_callback)