# -*- coding: utf-8 -*-
"""엠엘류게임.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8wGcAgG5OGJ4EYSYQugZQE3p_HQV4p_
"""

# app.py
import streamlit as st
from kiwipiepy import Kiwi

# ──────────────────────────────────────────────────────
# 기본 설정
# ──────────────────────────────────────────────────────
st.set_page_config(
    page_title="MLU-w를 맞혀라! (kiwipiepy 기반)",
    layout="centered"
)

st.title("MLU-w를 맞혀라!♡ (kiwipiepy 기반)")
st.markdown("제시된 문장의 MLU-w(어절 기준)를 계산하여 입력하세요.")

# ──────────────────────────────────────────────────────
# Kiwi 객체 캐시
# ──────────────────────────────────────────────────────
@st.cache_resource
def get_kiwi():
    return Kiwi()

kiwi = get_kiwi()

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수 (어절 기준)
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]

    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = []

    for i, utt in enumerate(utterances):
        # 어절 기준 계산
        word_count = len(utt.split())
        utterance_word_counts.append(word_count)

        utterance_details.append(
            f" - 발화 {i+1}: '{utt}' (어절수: {word_count})"
        )

    total_utterances = len(utterances)
    average_word_count = sum(utterance_word_counts) / total_utterances
    mlu_w = round(average_word_count, 2)

    return {
        "utterance_details": utterance_details,
        "total_utterances": total_utterances,
        "mlu_w": mlu_w
    }, utterances


# ──────────────────────────────────────────────────────
# 문제 데이터
# ──────────────────────────────────────────────────────
questions = [
    {"sentence": "엄마 저 피자랑 고구마 주세요. 맛있게 구워 주세요.", "mluw": 4.5},
    {"sentence": "형아 나 밥. 나 배고파.", "mluw": 2.0},
    {"sentence": "아빠랑 공원에 갔어요. 시소 타고 미끄럼틀도 탔어요.", "mluw": 4.0},
    {"sentence": "맛있는 케이크 먹고 싶어요. 선물로 주세요.", "mluw": 3.0},
    {"sentence": "엄마 하늘 봐요. 하늘에 반짝해요. 별이 정말 예뻐요.", "mluw": 2.67},
    {"sentence": "동생이 내 장난감 가지고 놀아요. 저 화가 났어요.", "mluw": 3.5},
]

# ──────────────────────────────────────────────────────
# 세션 상태 초기화
# ──────────────────────────────────────────────────────
if "current_question_index" not in st.session_state:
    st.session_state.current_question_index = 0

if "feedback_message" not in st.session_state:
    st.session_state.feedback_message = ""

if "result_message" not in st.session_state:
    st.session_state.result_message = ""

if "show_input" not in st.session_state:
    st.session_state.show_input = True

if "show_next_button" not in st.session_state:
    st.session_state.show_next_button = False

if "user_mluw_input" not in st.session_state:
    st.session_state.user_mluw_input = ""

if "initial_load" not in st.session_state:
    st.session_state.initial_load = True


# ──────────────────────────────────────────────────────
# 게임 함수
# ──────────────────────────────────────────────────────
def load_question():
    st.session_state.feedback_message = ""
    st.session_state.result_message = ""
    st.session_state.user_mluw_input = ""
    st.session_state.show_input = True
    st.session_state.show_next_button = False


def check_answer_callback():
    q_data = questions[st.session_state.current_question_index]
    user_answer = st.session_state.user_mluw_input.strip()

    if not user_answer:
        st.session_state.feedback_message = (
            "<p style='color:red; font-weight:bold;'>MLU-w 값을 입력해주세요!</p>"
        )
        return

    try:
        user_mluw = float(user_answer)
    except ValueError:
        st.session_state.feedback_message = (
            "<p style='color:red; font-weight:bold;'>유효한 숫자를 입력해주세요!</p>"
        )
        return

    correct_mluw = q_data["mluw"]

    st.session_state.result_message = (
        f"<p>제시 문장: \"{q_data['sentence']}\"</p>"
    )

    if abs(user_mluw - correct_mluw) < 0.01:
        st.session_state.feedback_message = (
            "<p style='color:green; font-weight:bold;'>정답입니다!</p>"
        )
    else:
        st.session_state.feedback_message = (
            "<p style='color:red; font-weight:bold;'>오답입니다.</p>"
        )

    st.session_state.result_message += (
        f"<p style='color:#555;'>정답 MLU-w: {correct_mluw}</p>"
    )

    st.session_state.show_input = False
    st.session_state.show_next_button = True


def next_problem_callback():
    st.session_state.current_question_index += 1
    load_question()


def reset_game_callback():
    st.session_state.current_question_index = 0
    load_question()


# ──────────────────────────────────────────────────────
# 초기 문제 로드
# ──────────────────────────────────────────────────────
if st.session_state.initial_load:
    load_question()
    st.session_state.initial_load = False


# ──────────────────────────────────────────────────────
# UI
# ──────────────────────────────────────────────────────
if st.session_state.current_question_index >= len(questions):
    st.header("모든 문제를 다 풀었습니다!")
    st.write("아래 '처음으로' 버튼을 눌러 다시 시작하세요.")

    st.button("처음으로", on_click=reset_game_callback)

else:
    q_data = questions[st.session_state.current_question_index]

    st.subheader(f'문제: "{q_data["sentence"]}"')

    if st.session_state.show_input:
        st.text_input(
            "MLU-w를 입력하세요",
            key="user_mluw_input"
        )

        st.button(
            "정답 확인",
            on_click=check_answer_callback
        )

    st.markdown(
        st.session_state.feedback_message,
        unsafe_allow_html=True
    )

    st.markdown(
        st.session_state.result_message,
        unsafe_allow_html=True
    )

    col1, col2 = st.columns(2)

    with col1:
        if st.session_state.show_next_button:
            st.button(
                "다음으로",
                on_click=next_problem_callback
            )

    with col2:
        st.button(
            "처음으로",
            on_click=reset_game_callback
        )